name: system_info_ml
description: Provides easy access to useful information about the system (architecture, bitness, kernel, memory, operating system, CPU, user).
version: 1.0.0
repository: https://github.com/maks/system_info_ml

environment:
  sdk: ^3.0.5

dependencies:
  file_utils: ^1.0.1
  path: ^1.8.3

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
